# Generated by Django 5.1 on 2024-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=50)),
                ('contact', models.IntegerField(default='')),
                ('mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
